on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    tags:
      - "v*"
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Cache yarn dependencies
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **/node_modules
          key: ${GITHUB_REF##*/}-yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn
      - run: npx oclif pack tarballs --no-xz
      - run: ls ./dist
#      - name: bump package version
#        run: |
#          npm version ${{ env.RELEASE_VERSION }} --git-tag-version=false
#      - name: actually_publish
#        run: npm publish --access public
#        env:
#          NODE_AUTH_TOKEN: "${{ secrets.NPM_PUBLISH_TOKEN }}"
#      - uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          prerelease: false
#          files: |
#            ./dist/*.tar.gz
#            ./dist/*.tar.xz
