on:
  release:
    types:
      - created
jobs:
  publish_sdk:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install dependencies
        run: npm install
      - name: bump package version
        run: npm version ${{ env.RELEASE_VERSION }}
      - name: actually_publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_PUBLISH_TOKEN }}"
